addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.5")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"        % "1.14")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.4.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.2.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"% "0.9.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.5.1")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.5.0")